//en
let enSubs = {
  "nest": "Nest",
  "polygon": "Polygon",
  "getSpawnReport": "Get spawn report",
  "removeMap": "Remove from map",
  "exportPolygon": "Export polygon",
  "exportVP": "Export visible points (CSV)",
  "countVP": "Count Visible points",
  "copyClipboard": "Copy to clipboard",
  "poiViewer": "Wayfarer mode",
  "routeGenerator": "Planning mode",
  "hideGyms": "Hide gyms",
  "showGyms": "Show gyms",
  "hidePokestops": "Hide pokestops",
  "showPokestops": "Show pokestops",
  "hidePokestopRange": "Hide pokestop range",
  "showPokestopRange": "Show pokestop range",
  "hideSpawnpoints": "Hide spawnpoints",
  "showSpawnpoints": "Show spawnpoints",
  "showAllPOIS": "Show all points",
  "showUnknownPOIS": "Show unknown points only",
  "hideViewingCells": "Hide viewing cells",
  "showViewingCells": "Show viewing cells",
  "enableManualCircle": "Enable manual circle mode",
  "disableManualCircle": "Disable manual circle mode",
  "importOSM": "Import nests from OSM",
  "importPolygon": "Import polygon",
  "importInstance": "Import instance",
  "importAdBounds": "Import administrative boundaries",
  "importSubmissions": "Import POIs",
  "poiData": "POI data in format: lat, lng, title",
  "csvOpener": "or select a CSV file:",
  "submissionRangeCheck": "Show 20m range for Wayfarer submissions",
  "clearRoute": "Clear route",
  "clearShapes": "Clear all shapes",
  "clearSubs": "Delete POIs",
  "generateRoute": "Generate circles (bootstrap)",
  "generateOptimizedRoute": "Generate optimized circles",
  "getOutput": "Get output",
  "openSettings": "Open settings",
  "delete": "Delete",
  "noData": "No data available.",
  "exEligible": " (ex-eligible)",
  "despawnTime": " Despawn time: ",
  "unknownDespawnTime": " unknown despawn time ",
  "count": "Count: ",
  "countTotal": "Count total: ",
  "countGyms": "Count gyms: ",
  "countStops": "Count stops: ",
  "countSpawnpoints": "Count spawnpoints: ",
  "spawnReport": "Spawn report - ",
  "unnamed": "unnamed",
  "at": "at",
  "skipped": " skipped, no data",
  "nestReport": "Nest report - all nests in view",
  "settings": "Settings",
  "routeOptAtt": "Route optimization attempts:",
  "tries": "Tries",
  "s2cells0": "Red, level:",
  "s2cells1": "Blue, level 14",
  "s2cells2": "Green, level 17",
  "s2CountPOI": "Show POI count",
  "circleRadius": "Circle radius:",
  "other": "other:",
  "lastNestMigration": "Last nest migration:",
  "spawnReportLimit": "Spawn report limit:",
  "spawnReportLimitExp": "Pokemon (0 for unlimited)",
  "selectLanguage": "Select language:",
  "chooseTileset": "Choose tileset:",
  "ownTileset": "Own tileset",
  "close": "Close",
  "output": "Output",
  "generatedRoute": "Generated route:",
  "getAllNests": "Get all nest reports",
  "countPoints": "Count points in circles",
  "optimize": "Optimize!",
  "optimizeGyms": "Optimize for gyms",
  "optimizePokestops": "Optimize for pokestops",
  "optimizeSpawnpoints": "Optimize for all spawnpoints",
  "optimizeUnknownSpawnpoints": "Optimize for spawnpoints without TTH",
  "on": "On",
  "off": "Off",
  "optimizePiP": "Optimize points in polygons",
  "optimizePiNP": "Optimize points in nest polygons",
  "optimizePiC": "Optimize points in circles",
  "getOptimization": "Get optimization",
  "copied": "Copied!",
  "selectInstance": "Select an instance:",
  "instanceColor": "Instance color:",
  "polygonColor": "Polygon color:",
  "polygonDataType": "Polygon data type:",
  "coordinateList": "Coordinate list: (latitude,longitude on each new line)",
  "geoJson": "GeoJSON",
  "poracle": "PoracleJS format",
  "polygonData": "Polygon data:",
  "import": "Import",
  "importNest": "Import as nest",
  "exportPolygonPoints": "Export polygon points (CSV)",
  "gyms": "Gyms:",
  "pokestops": "Pokestops:",
  "spawnpoints": "Spawnpoints:",
  "pokemon": "Pokémon",
  "getOwnLocation": "Get to my location!",
  "coordTypeUnsorted": "unsorted",
  "coordTypeSorted": "auto-sorted",
  "countCircles": "Number of circles:",
  "adBoundsHeader": "Select level of administrative boundaries",
  "adBounds1": "Counties",
  "adBounds2": "Cities",
  "adBounds3": "Wards",
  "getAdBounds": "Get polygons",
  "hideOldSpawnpoints": "Show old spawnpoints",
  "showOldSpawnpoints": "Hide old spawnpoints",
  "oldSpawnpointsTitle": "No spawnpoints last updated before:",
  "instanceMode": "Import circles in passive mode: ",
  "enableNewPOI": "Enable new POI",
  "disableNewPOI": "Disable new POI",
  "exportPOIs": "Export",
  "exportPOILabel": "Your POI has the following coordinates:",
  "outputAvgPt": "Average points per circle: ",
  "exportListCount": "Objects on exportlist: ",
  "chooseName": "Please choose a name!",
  "addToExport": "Add to exportlist",
  "removeFromExport": "Remove from exportlist",
  "name": "Name:",
  "saveFile": "Save as File",
  "ownRadius": "own radius",
  "drawnCircles": "drawn circles",
  "selectInstances": "Select instances",
  "importCirclesIns": "imported circles",
  "importCirclesHl": "Own coordinates: (latitude,longitude on each new line)",
  "importCirclesBtn": "Import circles",
  "showRoute": "Show route",
  "hideRoute": "Hide route",
  "newRoute": "New route",
  "hideQuests": "Hide stops with missing quests",
  "showQuests": "Show stops with missing quests",
  "questCheck": "Quest instances to be checked:",
  "questCheckButton": "Show it!",
  "showBorders": "Show instance borders",
  "generateWithS2Cells": "bootstrap <b>with</b> s2 cells",
  "lastUpdate": "Last update (UTC): ",
  "stop_deleted": "marked as deleted",
  "coords": "Coordinates",
  "drawPolygon": "Draw a polygon",
  "drawCircle": "Draw a free circle",
  "searchErr": "Location not found", 
  "searchCancel": "Cancel",
  "searchPlaceholder": "Search...",
  "editEdit": "Edit layers",
  "editEditDisabled": "No layers to edit",
  "oldDevices": "1gb devices",
  "circleID": "Circle ID:",
  "manualdbHint": "only usable with manualdb:",
  "importFromDB": "Import nests from db",
  "writeAllToDB": "Update nests in db",
  "nestOptions": "Nestoptions",
  "writeSuccess": "Nest(s) successfully added/updated!",
  "writeToDB": "Write to db",
  "instanceLength": "Length of instance:",
  "area": "Area",
  "osmOptions": "OSM Options",
  "osmPark": "Park",
  "osmMeadow": "Meadow",
  "osmRecGround": "Recreation Ground",
  "osmGrass": "Grass",
  "osmPitch": "Pitch",
  "osmGolf": "Golf course",
  "osmPlayground": "Playground",
  "osmImport": "Import nests from OSM",
  "mergePolygons": "Merge visible polygons"
};
let enPokemon = ["Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard","Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree","Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate","Spearow","Fearow","Ekans","Arbok","Pikachu","Raichu","Sandshrew","Sandslash","Nidoran\u2640","Nidorina","Nidoqueen","Nidoran\u2642","Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat","Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck","Mankey","Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop","Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel","Geodude","Graveler","Golem","Ponyta","Rapidash","Slowpoke","Slowbro","Magnemite","Magneton","Farfetch\u2019d","Doduo","Dodrio","Seel","Dewgong","Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute","Exeggutor","Cubone","Marowak","Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan","Horsea","Seadra","Goldeen","Seaking","Staryu","Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon","Porygon","Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew","Chikorita","Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados","Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom","Marill","Azumarill","Sudowoodo","Politoed","Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown","Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa","Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour","Houndoom","Kingdra","Phanpy","Donphan","Porygon2","Stantler","Smeargle","Tyrogue","Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar","Lugia","Ho-Oh","Celebi","Treecko","Grovyle","Sceptile","Torchic","Combusken","Blaziken","Mudkip","Marshtomp","Swampert","Poochyena","Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Lotad","Lombre","Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper","Ralts","Kirlia","Gardevoir","Surskit","Masquerain","Shroomish","Breloom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask","Shedinja","Whismur","Loudred","Exploud","Makuhita","Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye","Mawile","Aron","Lairon","Aggron","Meditite","Medicham","Electrike","Manectric","Plusle","Minun","Volbeat","Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord","Numel","Camerupt","Torkoal","Spoink","Grumpig","Spinda","Trapinch","Vibrava","Flygon","Cacnea","Cacturne","Swablu","Altaria","Zangoose","Seviper","Lunatone","Solrock","Barboach","Whiscash","Corphish","Crawdaunt","Baltoy","Claydol","Lileep","Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Kecleon","Shuppet","Banette","Duskull","Dusclops","Tropius","Chimecho","Absol","Wynaut","Snorunt","Glalie","Spheal","Sealeo","Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Beldum","Metang","Metagross","Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys","Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape","Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew","Roserade","Cranidos","Rampardos","Shieldon","Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen","Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos","Gastrodon","Ambipom","Drifloon","Drifblim","Buneary","Lopunny","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor","Bronzong","Bonsly","Mime Jr.","Happiny","Chatot","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Riolu","Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Finneon","Lumineon","Mantyke","Snover","Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z","Gallade","Probopass","Dusknoir","Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus","Victini","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott","Dewott","Samurott","Patrat","Watchog","Lillipup","Herdier","Stoutland","Purrloin","Liepard","Pansage","Simisage","Pansear","Simisear","Panpour","Simipour","Munna","Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola","Boldore","Gigalith","Woobat","Swoobat","Drilbur","Excadrill","Audino","Timburr","Gurdurr","Conkeldurr","Tympole","Palpitoad","Seismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Venipede","Whirlipede","Scolipede","Cottonee","Whimsicott","Petilil","Lilligant","Basculin","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan","Maractus","Dwebble","Crustle","Scraggy","Scrafty","Sigilyph","Yamask","Cofagrigus","Tirtouga","Carracosta","Archen","Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita","Gothitelle","Solosis","Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck","Emolga","Karrablast","Escavalier","Foongus","Amoonguss","Frillish","Jellicent","Alomomola","Joltik","Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinklang","Tynamo","Eelektrik","Eelektross","Elgyem","Beheeyem","Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal","Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon","Golett","Golurk","Pawniard","Bisharp","Bouffalant","Rufflet","Braviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon","Larvesta","Volcarona","Cobalion","Terrakion","Virizion","Tornadus","Thundurus","Reshiram","Zekrom","Landorus","Kyurem","Keldeo","Meloetta","Genesect","Chespin","Quilladin","Chesnaught","Fennekin","Braixen","Delphox","Froakie","Frogadier","Greninja","Bunnelby","Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa","Vivillon","Litleo","Pyroar","Flabébé","Floette","Florges","Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Honedge","Doublade","Aegislash","Spritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle","Barbaracle","Skrelp","Dragalge","Clauncher","Clawitzer","Helioptile","Heliolisk","Tyrunt","Tyrantrum","Amaura","Aurorus","Sylveon","Hawlucha","Dedenne","Carbink","Goomy","Sliggoo","Goodra","Klefki","Phantump","Trevenant","Pumpkaboo","Gourgeist","Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion","Rowlet","Dartrix","Decidueye","Litten","Torracat","Incineroar","Popplio","Brionne","Primarina","Pikipek","Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug","Vikavolt","Crabrawler","Crabominable","Oricorio","Cutiefly","Ribombee","Rockruff","Lycanroc","Wishiwashi","Mareanie","Toxapex","Mudbray","Mudsdale","Dewpider","Araquanid","Fomantis","Lurantis","Morelull","Shiinotic","Salandit","Salazzle","Stufful","Bewear","Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod","Sandygast","Palossand","Pyukumuku","Type: Null","Silvally","Minior","Komala","Turtonator","Togedemaru","Mimikyu","Bruxish","Drampa","Dhelmise","Jangmo-o","Hakamo-o","Kommo-o","Tapu Koko","Tapu Lele","Tapu Bulu","Tapu Fini","Cosmog","Cosmoem","Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana","Guzzlord","Necrozma","Magearna","Marshadow"];
