//fr
let frSubs = {
  "nest": "Nid",
  "polygon": "Polygone",
  "getSpawnReport": "Rapport de spawns",
  "removeMap": "Supprime du plan",
  "exportPolygon": "Exporte polygone",
  "exportVP": "Exporte points visibles",
  "countVP": "Compte points visibles",
  "copyClipboard": "Copier",
  "poiViewer": "Mode Wayfarer",
  "routeGenerator": "Mode de planification",
  "hideGyms": "Cache les arènes",
  "showGyms": "Montre les arènes",
  "hidePokestops": "Cache les pokéstops",
  "showPokestops": "Montre les pokéstops",
  "hidePokestopRange": "Cache la zone des pokéstops",
  "showPokestopRange": "Montre la zone des pokéstops",
  "hideSpawnpoints": "Cache les spawnpoints",
  "showSpawnpoints": "Montre les spawnpoints",
  "showAllPOIS": "Montre tous les POIs",
  "showUnknownPOIS": "Montre seulement les points inconnus",
  "hideViewingCells": "Cache cells s2",
  "showViewingCells": "Montre cells s2",
  "enableManualCircle": "Active le mode manuel du cercle",
  "disableManualCircle": "Désactive le mode manuel du cercle",
  "importOSM": "Importer les nests d'OSM",
  "importPolygon": "Importe polygone",
  "importInstance": "Importe d'instances",
  "importAdBounds": "Importe de frontières administratives",
  "importSubmissions": "Importe de POIs",
  "poiData": "POI data en format: lat, lng, title",
  "csvOpener": "ou selectionne un fichier CSV:",
  "submissionRangeCheck": "Montre la zone de 20m pour soumissions Wayfarer",
  "clearRoute": "Dégage la route",
  "clearShapes": "Dégage tous",
  "clearSubs": "Supprime les POIs",
  "generateRoute": "Génère des cercles (bootstrap)",
  "generateOptimizedRoute": "Génère des cercles optimisés",
  "getOutput": "Obtiens le résultat",
  "openSettings": "Ouvre les paramètres",
  "delete": "Supprime",
  "noData": "aucune donnée disponible.",
  "exEligible": " (ex-eligible)",
  "despawnTime": " Moment de despawn: ",
  "unknownDespawnTime": " moment de despawn inconnu ",
  "count": "Compte: ",
  "countTotal": "Compte total: ",
  "countGyms": "Compte d'arènes: ",
  "countStops": "Compte de stops: ",
  "countSpawnpoints": "Compte des spawnpoints: ",
  "spawnReport": "Rapport de spawns - ",
  "unnamed": "sans nom",
  "at": "à",
  "skipped": " sauté, pas de données",
  "nestReport": "Rapport de nids - tous les nids en vue",
  "settings": "Paramètres",
  "routeOptAtt": "Essais d'optimisation de la route:",
  "tries": "Essais",
  "s2cells0": "Rouge, level:",
  "s2cells1": "Bleu, level 14",
  "s2cells2": "Vert, level 17",
  "s2CountPOI": "Montre compte de POIs",
  "circleRadius": "Rayon du cercle:",
  "other": "autres:",
  "lastNestMigration": "Dernières migration de nids:",
  "spawnReportLimit": "limit du rapport des spawns:",
  "spawnReportLimitExp": "Pokémon (0 pour illimité)",
  "selectLanguage": "Choisis langue:",
  "chooseTileset": "Choisis tileset:",
  "ownTileset": "Tileset propre",
  "close": "Ferme",
  "output": "Résultat",
  "generatedRoute": "Route générée:",
  "getAllNests": "Obtiens tous les rapports de nids",
  "countPoints": "Compte les points à l'intérieur des cercles",
  "optimize": "Optimise!",
  "optimizeGyms": "Optimise pour les arènes",
  "optimizePokestops": "Optimise pour les pokéstops",
  "optimizeSpawnpoints": "Optimise pour tous les spawnpoints",
  "optimizeUnknownSpawnpoints": "Optimise pour les spawnpoints sans TTH",
  "on": "Activé",
  "off": "Desactivé",
  "optimizePiP": "Optimise les points dans les polygons",
  "optimizePiNP": "Optimise les points dans les polygons de nid",
  "optimizePiC": "Optimise les points dans les cercles",
  "getOptimization": "Obtiens l'optimisation",
  "copied": "Copié!",
  "selectInstance": "Choisis une instance:",
  "instanceColor": "Couleur de l'instance:",
  "polygonColor": "Couleur du polygone:",
  "polygonDataType": "Type de données de polygone:",
  "coordinateList": "List des coordinates: (latitude,longitude sur une ligne)",
  "geoJson": "GeoJSON",
  "poracle": "Format PoracleJS",
  "polygonData": "Données de polygone:",
  "import": "Importe",
  "importNest": "Importe comme nid",
  "exportPolygonPoints": "Exporte les points du polygone (CSV)",
  "gyms": "Arènes:",
  "pokestops": "Pokéstops:",
  "spawnpoints": "Spawnpoints:",
  "pokemon": "Pokémon",
  "getOwnLocation": "Localise moi!",
  "coordTypeUnsorted": "non triés",
  "coordTypeSorted": "auto-triés",
  "countCircles": "Compte de cercles:",
  "adBoundsHeader": "Choisis le niveau de frontières administratives",
  "adBounds1": "Départements",
  "adBounds2": "Villes",
  "adBounds3": "Quartiers",
  "getAdBounds": "Obtiens les polygons",
  "hideOldSpawnpoints": "Montre les vieux spawnpoints",
  "showOldSpawnpoints": "Cache les vieux spawnpoints",
  "oldSpawnpointsTitle": "Pas de spawnpoints actualisés avant:",
  "instanceMode": "Importe les cercles en mode passive: ",
  "enableNewPOI": "Active nouveau POI",
  "disableNewPOI": "Désactive nouveau POI",
  "exportPOIs": "Exporte",
  "exportPOILabel": "Ton POI a les coordinates suivants:",
  "outputAvgPt": "Points par cercle en moyenne: ",
  "exportListCount": "Objets sur la liste d'export: ",
  "chooseName": "Choisis un nom!",
  "addToExport": "Ajoute sur la liste d'export",
  "removeFromExport": "Supprime de la liste d'export",
  "name": "Nom:",
  "saveFile": "Sauver comme fichier",
  "ownRadius": "rayon propre",
  "drawnCircles": "cercles dessinés",
  "selectInstances": "Choisis les instances",
  "importCirclesIns": "cercles importés",
  "importCirclesHl": "Coordinates propre: (latitude,longitude on each new line)",
  "importCirclesBtn": "Cercles importés",
  "showRoute": "Montre route",
  "hideRoute": "Cache route",
  "newRoute": "Nouveau route",
  "hideQuests": "Montre stops sans quest",
  "showQuests": "Cache stops sans quest",
  "questCheck": "Instances à vérifier:",
  "questCheckButton": "Montre!",
  "showBorders": "Montre les frontières des instances",
  "generateWithS2Cells": "Bootstrap <b>avec</b> cells s2",
  "lastUpdate": "Dernière actualisation (UTC): ",
  "stop_deleted": "marqué pour suppression",
  "coords": "Coordinates",
  "drawPolygon": "Tire un polygon",
  "drawCircle": "Tire un cercle libre",
  "searchErr": "Location pas connu", 
  "searchCancel": "Annuler",
  "searchPlaceholder": "Chercher...",
  "editEdit": "Editer les couches",
  "editEditDisabled": "Pas de couche à éditer",
  "oldDevices": "Appareils 1go",
  "circleID": "ID du cercle:",
  "manualdbHint": "seulement utilisable avec manualdb:",
  "importFromDB": "Importer les nids de la bd",
  "writeAllToDB": "Actualise les nids en bd",
  "nestOptions": "Options de nid",
  "writeSuccess": "Réussi à actualiser/inscrire le(s) nid(s)",
  "writeToDB": "Inscrire en bd",
  "instanceLength": "Longueur de l'instance:",
  "area": "Superficie",
  "osmOptions": "Options OSM",
  "osmPark": "Parc",
  "osmMeadow": "Prairie",
  "osmRecGround": "Terrain de loisirs",
  "osmGrass": "Pâturage",
  "osmPitch": "Terrain de jeu",
  "osmGolf": "Parcours de golf",
  "osmPlayground": "Terrain de jeux",
  "osmImport": "Importer les nids d'OSM",
  "mergePolygons": "Fussioner les polygons visibles"
};
let frPokemon = ["Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard","Squirtle","Wartortle","Blastoise","Caterpie","Metapod","Butterfree","Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot","Rattata","Raticate","Spearow","Fearow","Ekans","Arbok","Pikachu","Raichu","Sandshrew","Sandslash","Nidoran\u2640","Nidorina","Nidoqueen","Nidoran\u2642","Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Ninetales","Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat","Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck","Mankey","Primeape","Growlithe","Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop","Machoke","Machamp","Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel","Geodude","Graveler","Golem","Ponyta","Rapidash","Slowpoke","Slowbro","Magnemite","Magneton","Farfetch\u2019d","Doduo","Dodrio","Seel","Dewgong","Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee","Hypno","Krabby","Kingler","Voltorb","Electrode","Exeggcute","Exeggutor","Cubone","Marowak","Hitmonlee","Hitmonchan","Lickitung","Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangaskhan","Horsea","Seadra","Goldeen","Seaking","Staryu","Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Tauros","Magikarp","Gyarados","Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon","Porygon","Omanyte","Omastar","Kabuto","Kabutops","Aerodactyl","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew","Chikorita","Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr","Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados","Crobat","Chinchou","Lanturn","Pichu","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom","Marill","Azumarill","Sudowoodo","Politoed","Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora","Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown","Wobbuffet","Girafarig","Pineco","Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor","Shuckle","Heracross","Sneasel","Teddiursa","Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola","Remoraid","Octillery","Delibird","Mantine","Skarmory","Houndour","Houndoom","Kingdra","Phanpy","Donphan","Porygon2","Stantler","Smeargle","Tyrogue","Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey","Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar","Lugia","Ho-Oh","Celebi","Treecko","Grovyle","Sceptile","Torchic","Combusken","Blaziken","Mudkip","Marshtomp","Swampert","Poochyena","Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon","Beautifly","Cascoon","Dustox","Lotad","Lombre","Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingull","Pelipper","Ralts","Kirlia","Gardevoir","Surskit","Masquerain","Shroomish","Breloom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask","Shedinja","Whismur","Loudred","Exploud","Makuhita","Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye","Mawile","Aron","Lairon","Aggron","Meditite","Medicham","Electrike","Manectric","Plusle","Minun","Volbeat","Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord","Numel","Camerupt","Torkoal","Spoink","Grumpig","Spinda","Trapinch","Vibrava","Flygon","Cacnea","Cacturne","Swablu","Altaria","Zangoose","Seviper","Lunatone","Solrock","Barboach","Whiscash","Corphish","Crawdaunt","Baltoy","Claydol","Lileep","Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Kecleon","Shuppet","Banette","Duskull","Dusclops","Tropius","Chimecho","Absol","Wynaut","Snorunt","Glalie","Spheal","Sealeo","Walrein","Clamperl","Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Beldum","Metang","Metagross","Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys","Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape","Piplup","Prinplup","Empoleon","Starly","Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew","Roserade","Cranidos","Rampardos","Shieldon","Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen","Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos","Gastrodon","Ambipom","Drifloon","Drifblim","Buneary","Lopunny","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor","Bronzong","Bonsly","Mime Jr.","Happiny","Chatot","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Riolu","Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Finneon","Lumineon","Mantyke","Snover","Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth","Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z","Gallade","Probopass","Dusknoir","Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus","Victini","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott","Dewott","Samurott","Patrat","Watchog","Lillipup","Herdier","Stoutland","Purrloin","Liepard","Pansage","Simisage","Pansear","Simisear","Panpour","Simipour","Munna","Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola","Boldore","Gigalith","Woobat","Swoobat","Drilbur","Excadrill","Audino","Timburr","Gurdurr","Conkeldurr","Tympole","Palpitoad","Seismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Venipede","Whirlipede","Scolipede","Cottonee","Whimsicott","Petilil","Lilligant","Basculin","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan","Maractus","Dwebble","Crustle","Scraggy","Scrafty","Sigilyph","Yamask","Cofagrigus","Tirtouga","Carracosta","Archen","Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita","Gothitelle","Solosis","Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck","Emolga","Karrablast","Escavalier","Foongus","Amoonguss","Frillish","Jellicent","Alomomola","Joltik","Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinklang","Tynamo","Eelektrik","Eelektross","Elgyem","Beheeyem","Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal","Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon","Golett","Golurk","Pawniard","Bisharp","Bouffalant","Rufflet","Braviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon","Larvesta","Volcarona","Cobalion","Terrakion","Virizion","Tornadus","Thundurus","Reshiram","Zekrom","Landorus","Kyurem","Keldeo","Meloetta","Genesect","Chespin","Quilladin","Chesnaught","Fennekin","Braixen","Delphox","Froakie","Frogadier","Greninja","Bunnelby","Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa","Vivillon","Litleo","Pyroar","Flabébé","Floette","Florges","Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Honedge","Doublade","Aegislash","Spritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle","Barbaracle","Skrelp","Dragalge","Clauncher","Clawitzer","Helioptile","Heliolisk","Tyrunt","Tyrantrum","Amaura","Aurorus","Sylveon","Hawlucha","Dedenne","Carbink","Goomy","Sliggoo","Goodra","Klefki","Phantump","Trevenant","Pumpkaboo","Gourgeist","Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion","Rowlet","Dartrix","Decidueye","Litten","Torracat","Incineroar","Popplio","Brionne","Primarina","Pikipek","Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug","Vikavolt","Crabrawler","Crabominable","Oricorio","Cutiefly","Ribombee","Rockruff","Lycanroc","Wishiwashi","Mareanie","Toxapex","Mudbray","Mudsdale","Dewpider","Araquanid","Fomantis","Lurantis","Morelull","Shiinotic","Salandit","Salazzle","Stufful","Bewear","Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod","Sandygast","Palossand","Pyukumuku","Type: Null","Silvally","Minior","Komala","Turtonator","Togedemaru","Mimikyu","Bruxish","Drampa","Dhelmise","Jangmo-o","Hakamo-o","Kommo-o","Tapu Koko","Tapu Lele","Tapu Bulu","Tapu Fini","Cosmog","Cosmoem","Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana","Guzzlord","Necrozma","Magearna","Marshadow"];
